#!/bin/bash
#SBATCH --job-name=moestudentteacher
#SBATCH --output=moestudentteacher_%j.out
#SBATCH --error=moestudentteacher_%j.err
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=gpuA40x4
#SBATCH --gres=gpu:1
#SBATCH --mem=40G
#SBATCH --account=bbjr-delta-gpu

# Load conda environment
source ~/miniconda3/etc/profile.d/conda.sh
conda activate pytorch_env2

# Change to the notebooks directory
cd /u/eboix/moe_experiment

# Run the deception generation script

# parser.add_argument('--d', type=int, default=256, help='Input dimension')
# parser.add_argument('--k1', type=int, default=2, help='Number of experts for teacher model')
# parser.add_argument('--num_experts1', type=int, default=4, help='Total number of experts for teacher model')
# parser.add_argument('--active_neurons1', type=int, default=256, help='Number of active neurons for teacher model')
# parser.add_argument('--k2', type=int, default=4, help='Number of experts for student model')
# parser.add_argument('--num_experts2', type=int, default=8, help='Total number of experts for student model')
# parser.add_argument('--active_neurons2', type=int, default=320, help='Number of active neurons for student model')
# parser.add_argument('--num_epochs', type=int, default=100, help='Number of epochs')
# parser.add_argument('--lr', type=float, default=1e-3, help='Learning rate')
# parser.add_argument('--batch_size', type=int, default=2048, help='Batch size')
# parser.add_argument('--trial', type=int, default=0, help='Trial number')
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 2 --num_experts2 4 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 4 --num_experts2 8 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 6 --num_experts2 12 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 8 --num_experts2 16 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 10 --num_experts2 20 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 12 --num_experts2 24 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 14 --num_experts2 28 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 2 --num_experts1 4 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 4 --num_experts1 8 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 6 --num_experts1 12 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 8 --num_experts1 16 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 10 --num_experts1 20 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 12 --num_experts1 24 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 14 --num_experts1 28 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.001                         --batch_size 2048                         --trial 0
srun python moe_student_teacher.py --d 256                         --k1 16 --num_experts1 32 --active_neurons1 256                         --k2 16 --num_experts2 32 --active_neurons2 320                         --num_epochs 100                         --lr 0.01                         --batch_size 2048                         --trial 0